volumes:
  data:
services:
  pg:
    env_file: .env
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    container_name: app
    env_file: .env
    build: .
    command: ["bash", "start.sh"]
    ports:
      - 8000:8000
    depends_on:
      - pg



